### ISSUE TITLE
Display server startup and request confirmation

### ISSUE THREAD

**Issue by byrnereese** [ringcentral/ringcentral-chatbot-js#10]
Upon starting the server today, the framework displays nothing to the console. I recommend the framework output to the console a few details, e.g.

> $ node -r dotenv/config express.js
> Server listening at http://localhost:3000
> Direct requests to http://ngrok.io/jfdslkjsdjkljsldkj
> Received request: PUT /admin/setup-database 200
> Received request: GET /bot/oauth - 200

This feedback would help the developer feel comfortable that things are working properly.

**Comment by tylerlong** [comment]
It is supported now:

```
$ node -r dotenv-override-true/config express.js
Bot service listening on port 3000
Please set your RingCentral app redirect URI to https://244b62f9.ngrok.io/bot/oauth
PUT /admin/setup-database 200 0 - 35.900 ms
PUT /admin/setup-database 200 0 - 3.387 ms
```
