### ISSUE TITLE
Clear and Concrete Starting Point

### ISSUE THREAD

**Issue by dibyenduroy** [ringcentral/ringcentral-chatbot-js#13]
It would be good to have a clear and concrete starting point. Currently, it seems there are multiple options and links on the page. One quick fix could be to just have the quickstarts at them and move all the other content down below so that when a user visits the page it would be clear where to navigate and for any additional links they can visit them later.

**Comment by tylerlong** [comment]
Done. I've made the quick start tutorials prominent in the readme page.
