### ISSUE TITLE
Expose original `message` to developer

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/ringcentral-chatbot-js#2]
In case developer want to access the original message, for example, developer want the bot only response to msg with `@{bot}`. Developer could do this from this `PostAdded` event in the end, but developer have to process the group info, user id.

```js
        case 'PostAdded':
          const result = await postAdded(message)
          if (result) {
            await handle({ type: 'Message4Bot', ...result, message })
          }
          break
```

**Comment by tylerlong** [comment]
The message is available.  https://github.com/ringcentral/ringcentral-chatbot-js/blob/master/src/apps/bot.js#L38

**Comment by zxdong262** [comment]
I mean, in line 38, there is no bot, group send to handler, user could build it, but if we send these info, use could save a lot of effort

**Comment by zxdong262** [comment]
#3 covers this topic I think.
