### ISSUE TITLE
When handling group join event, developer have to init bot inst/group info again?

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/ringcentral-chatbot-js#3]
Am I right? If so,
I suggest initing bot/group use info at `webhook handler` top position for all, make it common for user handler function

**Comment by tylerlong** [comment]
I don't quite understand this requirement.

**Comment by tylerlong** [comment]
For Group Joined message, I didn't do any special thing for developer. Developer needs to analyze the event and write custom code himself. Like this: https://github.com/tylerlong/glip-crontab-chatbot/blob/master/src/eventHandler.js#L10

**Comment by tylerlong** [comment]
I think I got your point. There are two kinds of events: 

- "raw" events from Glip server side
- events created by me, such as "Message4Bot". It is not issued by Glip server directly.

For "raw" events I don't make any pre-process, just deliver it to developer as it is. 

If I need to do preprocess, I would create a new event name instead. Don't want to change "raw" event directly.

**Comment by zxdong262** [comment]
I mean we could feed bot, group, userId etc and the raw event to handler function, in that case, user do not need write these, user do not want/need to know the event data detail since we have this framework.
```
      const botId = event.message.ownerId
      const bot = await Bot.findByPk(botId)
      const groupId = event.message.body.id
```

**Comment by tylerlong** [comment]
I got your idea. We need to do this case by case. There are a couple of different events (GroupJoined is just one of them).  For other kinds of events, `const botId = event.message.ownerId` might be wrong (ownerId might not be botId). 

We can provide user with bot and group for common events, including GroupJoined.

**Comment by tylerlong** [comment]
I have made `bot` and `groupId` available for GroupJoined event: https://github.com/ringcentral/ringcentral-chatbot-js/commit/185d4c6816d627303809fbd9536954f62e83e88b
