### ISSUE TITLE
If skill handled message, main bot logic better know it.

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/ringcentral-chatbot-js#4]
So main bot logic do not need to know detail of every skill and properly skip default message.

**Comment by tylerlong** [comment]
What is "main bot logic"?   By design, message handing is following listener pattern. Every subscriber can choose to handle or ignore any message.

**Comment by zxdong262** [comment]
Example, I have a translate bot, 
before using ping skill, in main bot logic, respond to every `@bot message-can-not-understand` message with help message, after using skill `ping`, `@bot ping` will send a `pong` message, in my main bot logic, I will also send help message, if I know ping bot respond to `ping`, I could write if else about this, assuming many skills, I have to write a lot of if else and read every skill's command, it will not be right. So if skill already responde to user message, skill could send a true or something to notify main bot logic function that user message has match one skill, then user bot logic could skip handling user message.

**Comment by tylerlong** [comment]
Supported.

https://github.com/ringcentral/ringcentral-chatbot-js#catch-all-skill

https://github.com/ringcentral/ringcentral-chatbot-js/blob/master/test/skills.spec.js#L42-L49
