### ISSUE TITLE
Good ideas for new bots

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-chatbot-js#8]
Please add a new comment for each new idea.

**Comment by tylerlong** [comment]
Admin team of XMN office wants a survey bot.
Admin team conduct surveys almost every month.
Let's check the surveys they sent out and think about how can we support them on Glip platform.

Both @zxdong262 and me created a survey bot. But I don't think they are able to meet admin team's requirements. Mine is an article for developers, not friendly to non-technical. @zxdong262 's version lacks some core features: such as multi-question surveys and survey result aggregation.

So we need to talk to the admin team and see how can we proceed.

**Comment by tylerlong** [comment]
IT team of XMN office wants a "welcome bot".
The idea is simple: IT team has a Glip team to support employees. 
Whenever a new user joined the team, the bot send a predefined message and mention that user.

We can make it a little more generic: allow user to specify welcome messages for every Glip team. 

IT team might want a more powerful bot in the future: one could answer common support questions. But for now they only need this "welcome" feature.

**Comment by embbnux** [comment]
* A bot to help employee ask a leave
* A bot to help employee to create a dinner order

**Comment by linjunpop** [comment]
A chatbot to AT everyone in a group, as Glip itself, does not provide the facility to mention everyone.

**Comment by linjunpop** [comment]
A bot to generate invitation url for the Glip Team.

**Comment by linjunpop** [comment]
A bot to translate other participant's messages.

**Comment by Dianesuadmin** [comment]
1.Admin Team希望在Glip上增加机器人自动回复的功能。输入关键字，能够弹出对应的链接;
2.为保障信息隐蔽性，希望该功能能加载在员工与机器人的私人聊天框下，而不是在公司大群中;
3.为方便员工搜索关键字，在打开与机器人聊天的界面时，希望能自动弹出热门/推荐搜索词汇，搜索指引，contact window等信息。

**Comment by embbnux** [comment]
A bot to send kudos

**Comment by zxdong262** [comment]
以下是Admin团队对于自动回复的功能需求：
 
1.       输入关键字，弹出对应的回复；
2.       打开与Glip机器人的聊天页面，能够推荐热搜关键词汇；
3.       打开与Glip机器人的聊天页面，能够展示搜索菜单。根据菜单指引，可以获得更多信息；
4.       后台能够记录员工搜索的关键词汇，以便后期内容的补充或增加；
5.       保证员工与Glip机器人的聊天记录的隐私性，不被其它员工看见；
6.       员工与Glip机器人的往期聊天记录能够保留在聊天页面；
7.       给Admin管理员权限，方便更新回复内容。

Translate:
Admin team's requirements about FAQ bot:
1. Respond to keyword
2. When open chat with bot, bot gives keyword suggestions
3. Bot can give a search dropdown menu(ignore, can not be done)
4. Bot can adjust keywords order according use frequency
5. Bot will only support private chat
6. User can keep chat records in glip(just like regular chat with real user).
7. Admin team can edit/update keywords/answer list

**Comment by tylerlong** [comment]
Close this ticket. Since this is not the greatest way to collect ideas.
