### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by byrnereese** [ringcentral/ringcentral-chatbot-js#9]
I have been following the instructions for an express bot. I have stashed my code here: https://github.com/byrnereese/qs-chat-javascript

I am finding that the server does not respond to any request. I can see the request coming in via ngrok, but the server I start never returns. This is true for the setup-database step as well as responding to the bot auth step triggered by Add to Glip.

**Comment by tylerlong** [comment]
Could you provide the logs/screenshots from ngrok?   ngrok provides an admin page where you can see the request/response header, body.

**Comment by byrnereese** [comment]
<img width="1199" alt="Screen Shot 2019-03-08 at 1 38 06 PM" src="https://user-images.githubusercontent.com/28429/54057318-746aa200-41a7-11e9-9652-5ff31cc898c5.png">

**Comment by byrnereese** [comment]
Here is all I get:

```
PUT /admin/setup-database HTTP/1.1
Host: 163961f1.ngrok.io
Authorization: Basic YWRtaW46YWRtaW4=
User-Agent: curl/7.54.0
Accept: */*
X-Forwarded-Proto: https
X-Forwarded-For: 162.207.206.200
```

If I wait long enough enough the console reports:
```
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```

Even performing a simple GET on the URL returns nothing. The browser just hangs.

**Comment by tylerlong** [comment]
Confirmed it is a bug I introduced recently.

Fixed: https://github.com/ringcentral/ringcentral-chatbot-js/commit/3798f27effb6f7e6074fc2a7e83d0c28d973ea7a
